# used to address resources (stylesheets, javascript)
url: https://wwu-pi.github.io/tutorials

# lectures to be included when generating overview
# - use the directory name within the lectures directory
lectures:
 - acse
 - eai
 - mdsd
 - lsp

# contact data for each lecture is maintained here
# - use the same lecture name as above for lectures
# - the contact information is displayed as a footer on each page (landing page and tutorials)
#
# <lecture name>: use the same name as above
#   url: URL where personal contact information is available
#   name: contact name
contacts:
  acse:
    url: https://www.wi.uni-muenster.de/de/institut/gruppen/pi/personen/jan-ernsting
    name: Jan Ernsting
  eai:
    url: https://www.wi.uni-muenster.de/de/institut/gruppen/pi/personen/jan-ernsting
    name: Jan Ernsting
  mdsd:
    url: https://www.wi.uni-muenster.de/de/institut/gruppen/pi/personen/claus-alexander-usener
    name: Claus Alexander Usener
  lsp:
    url: https://www.wi.uni-muenster.de/department/groups/pi/people/jan-dagefoerde
    name: Jan Dageförde

# excluded from Jekyll conversion
exclude:
  - serve.*
  - shell.*
  - build.*

markdown: kramdown
